### ISSUE TITLE
Class 'Tungsten\FootJob\Commands' not found

### ISSUE THREAD

**Issue by Willoxey** [TungstenVn/FootJob#4]
Version: 3.14.1
I havent changed any source code, just downloaded and installed it on my server.
Lots of code... and then this error:
`13.07 05:56:18 [Server] INFO }[05:56:18] [Server thread/CRITICAL]: Error: "Class 'Tungsten\FootJob\Commands' not found" (EXCEPTION) in "plugins/FootJob-master/src/Tungsten/FootJob/FootJob" at line 20
13.07 05:56:18 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/PluginBase(116): Tungsten\FootJob\FootJob->onEnable()
13.07 05:56:18 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
13.07 05:56:18 [Server] Server thread/DEBUG #2 src/pocketmine/Server(1787): pocketmine\plugin\PluginManager->enablePlugin(object Tungsten\FootJob\FootJob)
13.07 05:56:18 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1773): pocketmine\Server->enablePlugin(object Tungsten\FootJob\FootJob)
13.07 05:56:18 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1586): pocketmine\Server->enablePlugins(integer 1)
13.07 05:56:18 [Server] Server thread/DEBUG #5 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
13.07 05:56:18 [Server] Server thread/DEBUG #6 src/pocketmine/PocketMine(304): pocketmine\server()
13.07 05:56:18 [Server] Server thread/DEBUG #7 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)
13.07 05:56:18 [Server] Server thread/INFO Disabling FootJob v20.5.30`

**Comment by AngelliaX** [comment]
can you try going to Commands.php and change the first line from ``<?`` to ``<?php``

**Comment by AngelliaX** [comment]
does it work now

**Comment by Willoxey** [comment]
Yeah! it's working now.
That's why i closed the issue.
Thanks :)
