### ISSUE TITLE
pls fix

### ISSUE THREAD

**Issue by galaxytwenty** [TungstenVn/FootJob#9]
PLS fix

[Server thread/CRITICAL]: Error: "Call to a member function getPlayers() on null" (EXCEPTION) in "plugins/FootJob.phar/src/Tungsten/FootJob/RepeatingTask" at line 32

best greetz

**Comment by DJ13423** [comment]
im having the same problem after the 1.17.10 update

**Comment by YaNIND** [comment]
check new pull request
